import os
import sys
import time
import hashlib
from datetime import datetime

# ============================================================
# STEP 1: DETECT CONNECTED DRIVES (SIMPLIFIED FOR DEMO)
# ============================================================
def list_drives():
    """Lists all drives on the system. This is a simplified version."""



    
    drives = []
    # For Windows
    if os.name == 'nt':
        import string
        from ctypes import windll
        bitmask = windll.kernel32.GetLogicalDrives()
        for letter in string.ascii_uppercase:
            if bitmask & 1:
                drives.append(f"{letter}:\\")
            bitmask >>= 1
    # For Linux/Mac - This is a common approach
    else:
        # Look in the /sys/block directory to find drives
        if os.path.exists('/sys/block'):
            for device in os.listdir('/sys/block'):
                if device.startswith(('sd', 'hd', 'nvme')): # Common disk prefixes
                    drives.append(f"/dev/{device}")
        else:
            # Fallback: Use a common mount point list
            drives = ["/dev/sda", "/dev/sdb"] # Likely guesses for demo
    return drives

# ============================================================
# STEP 2: PERFORM A SIMPLE 1-PASS WIPE (WRITING ZEROS)
# ============================================================
def wipe_drive(drive_path, passes=1):
    """Wipes a test file on the drive by writing zeros to it."""
    # Create a test file on the drive instead of wiping the whole drive
    test_file = os.path.join(drive_path, "secure_erase_test.bin")
    total_size = 1024 * 1024 * 10  # 10 MB for DEMO
    block_size = 1024 * 64  # 64 KB
    zero_block = b'\0' * block_size

    try:
        print(f"[!] DEMO: This will create and wipe a test file on {drive_path}!")
        print(f"[!] File: {test_file}")
        confirm = input("[?] Type 'YES, WIPE' to confirm: ")
        if confirm != 'YES, WIPE':
            print("[!] Wipe cancelled.")
            return False

        print(f"[+] Creating and wiping test file on {drive_path}...")
        
        # Create and wipe the test file
        with open(test_file, 'wb') as file:
            written = 0
            while written < total_size:
                file.write(zero_block)
                written += len(zero_block)
                # Show a simple progress bar
                progress = (written / total_size) * 100
                sys.stdout.write(f"\r[+] Progress: [{('#' * int(progress//5)):<20}] {progress:.1f}%")
                sys.stdout.flush()
        
        # Delete the test file
        os.remove(test_file)
        print("\n[+] Wipe completed successfully. Test file created and destroyed.")
        return True

    except PermissionError:
        print(f"[!] ERROR: Permission denied for {drive_path}.")
        return False
    except Exception as e:
        print(f"[!] ERROR during wipe: {e}")
        return False

# ============================================================
# STEP 3: GENERATE A SIMPLE "CERTIFICATE"
# ============================================================
def generate_certificate(drive_path, algorithm="Quick Wipe (1-Pass Zero)"):
    """Generates a simple text certificate for the wipe operation."""
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    # Create a unique hash for this certificate based on time and drive
    cert_data = f"{drive_path}-{timestamp}-{algorithm}".encode()
    cert_hash = hashlib.sha256(cert_data).hexdigest()[:16]  # First 16 chars of hash

    certificate = f"""
=== SECURE-ERASE WIPE CERTIFICATE ===
Unique Certificate ID: {cert_hash}
Drive Wiped: {drive_path}
Wipe Algorithm: {algorithm}
Wipe Verification: Success - No recoverable data found (Simulated)
Date & Time: {timestamp}
Generated By: Secure-Erase MVP
=== END CERTIFICATE ===
"""
    # Save to a file
    filename = f"erase_certificate_{cert_hash}.txt"
    with open(filename, 'w') as f:
        f.write(certificate)
    print(f"[+] Certificate generated: {filename}")
    return certificate

# ============================================================
# MAIN PROGRAM LOGIC
# ============================================================
if __name__ == '__main__':
    print("=== Secure-Erase MVP ===")
    
    # 1. List Drives
    print("\n1. Detecting drives...")
    drives = list_drives()
    if not drives:
        print("[-] No drives found.")
        sys.exit(1)
        
    for i, drive in enumerate(drives):
        print(f"   {i+1}. {drive}")
    
    # 2. User Chooses Drive
    try:
        choice = int(input("\n2. Select the drive number to wipe: "))
        selected_drive = drives[choice-1]
    except (ValueError, IndexError):
        print("[!] Invalid selection.")
        sys.exit(1)
    
    # 3. Perform Wipe
    success = wipe_drive(selected_drive)
    
    # 4. If wipe was successful, generate a certificate
    if success:
        print("\n3. Generating certificate...")
        cert = generate_certificate(selected_drive)
        print(cert) # Print it to the screen
        print("\n[+] MVP Demo Complete! The concept is proven.")